### ISSUE TITLE
[BUG] Thickness Parameter

### ISSUE THREAD

**Issue by deloarts** [deloarts/pytia-bounding-box#22]
**Describe the bug**
The app cannot retrieve the thickness parameter anymore.
Trace:
```python
2023-07-11 15:37:48,222 pytia   ERROR    Couldn't retrieve parameter section_thickness from part: Item.value
Traceback (most recent call last):
  File "C:\Users\...\OneDrive\Python\pytia-bounding-box/pytia_bounding_box\app\helper.py", line 347, in get_parameter
    if self.part_document.parameters.exists(name):
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\pytia-bounding-box-w-rQ21Rs-py3.10\lib\site-packages\pytia\wrapper\parameters.py", line 98, in exists
    if self._parameters.item(i).name == name:
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\pytia-bounding-box-w-rQ21Rs-py3.10\lib\site-packages\pycatia\knowledge_interfaces\parameters.py", line 432, in item
    if isinstance(self.parameters.Item(index).value, bool):
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\pytia-bounding-box-w-rQ21Rs-py3.10\lib\site-packages\win32com\client\dynamic.py", line 638, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: Item.value
```

**Comment by deloarts** [comment]
Fixed in #24
